### ISSUE TITLE
Tag commits - go mod friendly

### ISSUE THREAD

**Issue by millergarym** [jpillora/opts#12]
Can you please tag working commits so that can be pointed at as a go module.

**Comment by jpillora** [comment]
Will do tonight! It's nearly ready :) final thing is slice of args help,
and enforcing slice of args min. Did a fairly large rewrite, most notably,
item is now a generic flag.Value

**Comment by jpillora** [comment]
Tagged https://github.com/jpillora/opts/tree/v0.1.0. Hopefully will release a v1 soon. Also thinking of a predictor `opts="k=v"` struct tag api. I think you mentioned this at some point, though might do `predict=files`, which is `predict=files:*`, ditto `dirs`.

**Comment by dolmen** [comment]
@millergarym You don't need tags for package to be usable with Go modules.
