### ISSUE TITLE
goopts: Create struct from existing help

### ISSUE THREAD

**Issue by millergarym** [jpillora/opts#14]
The help from Cobra based CLI command is pretty standardised.

This feature request is that goopts parsers this help and creates a struct (and maybe a proxy) to existing CLIs.

eg ` docker run --help | goopts parser_cobra_help > my_docker_run.go`

**Comment by jpillora** [comment]
Merged #13 into a new repo https://github.com/jpillora/opts-cli I think this should hold all code generation logic
