### ISSUE TITLE
API change - added Call - Tag required - v1.1.0

### ISSUE THREAD

**Issue by millergarym** [jpillora/opts#15]
Would be really nice if Go code could be auto checked for major and minor version suggestions.
Git hooks (pre-commit, pre-receive) would be a nice place to invoke these.

Without the tag it is difficult to spec this in go.mod.

**Comment by millergarym** [comment]
Ah, just saw v1.0.1.
But since you added features it should have been v1.1.0

**Comment by jpillora** [comment]
Kept it patch since there are a relatively low number of users atm

I think there's an api compatibility static analysis tool...
