### ISSUE TITLE
Runner Runner

### ISSUE THREAD

**Issue by millergarym** [jpillora/opts#2]
Should the runner interfaces be

A.
``` go
type runner1 interface {
	Run() error
}

type runner2 interface {
	Run()
}
```

Or

B.
``` go
type runner1 interface {
	Run() error
}

type runner2 interface {
	Run(args []string) error
}
```

It is possible to argue that B. is not needed as the client can always call `os.Args()`, but this implies the client need to parser / ignore parent args.  This complicates the client and might make custom completion quite difficult.

After having typed this, I think the answer might be `C.`. It complicates the library (not all that much) and simplifies the clients. 
C.
``` go
type runner1 interface {
	Run() error
}
type runner1b interface {
	Run()
}
type runner2 interface {
	Run(args []string) error
}
type runner2b interface {
	Run(args []string) error
}
```

Customer 1st FTW.
or is it
WTF over complicating things :-)

**Comment by millergarym** [comment]
Having a look at the code, what would be the semantics `Run(args []string)` and how difficult would it be to implement. Right now I think it is more WTF then FTW, needs use-cases before implementing.

**Comment by jpillora** [comment]
I think A. (with `error`) is okay initially, and we could move to C. eventually. The `[]args` versions could just short circuit `parse`, not do any parsing and just call `Run` with them. To keep API surface down, and provided a recommended way, I think we expose and document the `Run() error` interface and only mention the others in the doc comment.
