### ISSUE TITLE
UseEnv() should not apply to auto-generated flags such as --help

### ISSUE THREAD

**Issue by marco-m** [jpillora/opts#21]
Hello,

UseEnv() is quite handy. On the other hand, I would suggest that it should skip autogenerated flags, such as --help (probably the only auto-generated flag).

Rationale: setting an env var for --help doesn't make sense and is quite confusing:

```
  Usage: hello [options]

  Options:
  --file, -f   file to load (env FILE)
  --lines, -l  number of lines to show (env LINES)
  --help, -h   display help (env HELP)
```

I understand that the workaround is simply not to use `useEnv()` and to explicitly add to the single fields ``opts:"env"`` :-)

**Comment by jpillora** [comment]
Agreed, help having an env flag is a bug. Will fix

**Comment by marco-m** [comment]
thanks!
