### ISSUE TITLE
Parse() calls os.Exit(0) in case of parse error

### ISSUE THREAD

**Issue by marco-m** [jpillora/opts#22]
Hello,

I guess this is a design choice, but I would like the opposite, is there a way?

- Parse() exits with 1 in case of parse error related to argument (this I like)
- Parse() exits with 0 in case of parse error related to options (this I would like to change)

I would like:
- Parse() to always exit with a non-zero exit code in case of parse error.
- Even better I would like Parse() (or another function) not to exit behind my back and return a classic Go tuple with an error.

Rationale: any UNIX/POSIX command-line utility exits with non-zero in case of user calling it incorrectly.

Example with `cp` on macOS:

```
> cp a b ; echo $status
cp: a: No such file or directory
1
```
```
> cp ; echo $status
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
64
```
```
> cp -x; echo $status
cp: illegal option -- x
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
64
```

What are my options with `opts` ? Would you consider a PR ? Thanks!

**Comment by marco-m** [comment]
Hello @jpillora friendly ping :-)

**Comment by jpillora** [comment]
Oh yes, should indeed exit with 1, PR 😁 ?

**Comment by marco-m** [comment]
thanks!
