### ISSUE TITLE
Completion not implemented.

### ISSUE THREAD

**Issue by millergarym** [jpillora/opts#5]
The simple example in `example/cmdscomplete` doesn't seem to do anything.

``` go
func main() {

	bar := Bar{}
	b := opts.New(&bar).Name("bar")

	foo := Foo{}
	f := opts.New(&foo).Name("foo").AddCommand(b)

	config := Config{}
	opts.New(&config).
		Name("root").
		AddCommand(f).
		Complete().
		Parse().
		RunFatal()
}
```

The above example code made me thing of what would it mean if one added completion to a subcommand. I realised that AddCommand returns the parent, but what if someone wrote;
``` go
	ro := opts.New(&root{}).
		AddCommand(opts.New(&foo{}).Name("foo").Complete())
	ro.Parse().RunFatal()
```
Should this be an error, if so when.
If it isn't an error is there come sensible way of configuring completions to handle it, does the completions library cater for this?

**Comment by jpillora** [comment]
To simplify things, all `Opts` methods are basically dumb setters. They can call `errorf` which stores the error. The only place where this error is checked is `parse`, which always returns (never calls `Exit`). So, `Complete()` on a subcommand `parent != nil` should be an error yes. Will fix now :+1:

**Comment by jpillora** [comment]
Also, this example is a WIP, think I'll swap it to not use sub-commands, and just demo it working with flags
